service: mybackend

provider:
  name: aws
  runtime: nodejs10.x

functions:
  todos:
    handler: handler.getTodos
    events:
      - http:
          path: todos
          method: get
          cors: true
